url=jdbc:postgresql:microservicedb

referenceUrl=hibernate:spring:de.trettstadt.microservices.springbootmicroservice?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl&hibernate.implicit_naming_strategy=org.springframework.boot.hibernate.SpringImplicitNamingStrategy
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver

changeLogFile=db.changelog-master.yaml
diffChangeLogFile=db.changelog-diff.yaml
