apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "booking.fullname" . }}-config
  labels:
    {{- include "booking.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      profiles:
        active: {{ .Values.spring.profiles.active | quote }}
      config:
        import: "optional:file:/etc/config-secret/application.yaml"
      datasource:
        url: {{ .Values.database.url }}
        username: {{ .Values.database.username }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.oauth2.issuerUri }}
          client:
            registration:
              rooms:
                provider: keycloak
                client-id: {{ .Values.oauth2.clientId }}
                client-secret: {{ .Values.oauth2.clientSecret }}
            provider:
              keycloak:
                issuer-uri: {{ .Values.oauth2.issuerUri }}
    management:
      endpoint:
        health:
          probes:
            enabled: {{ .Values.actuator.health.probesEnabled }}
      endpoints:
        web:
          exposure:
            include: {{ .Values.actuator.endpoints.exposure.include | quote }}
      prometheus:
        metrics:
          export:
            enabled: {{ .Values.actuator.prometheus.metrics.export.enabled }}
      opentelemetry:
        tracing:
          export:
            otlp:
              transport: {{ .Values.actuator.opentelemetry.tracing.export.otlp.transport }}
              endpoint: {{ .Values.actuator.opentelemetry.tracing.export.otlp.endpoint }}
        logging:
          export:
            otlp:
              transport: {{ .Values.actuator.opentelemetry.logging.export.otlp.transport }}
              endpoint: {{ .Values.actuator.opentelemetry.logging.export.otlp.endpoint }}
      otlp:
        metrics:
          export:
            enabled: {{ .Values.actuator.opentelemetry.metrics.export.enabled }}
            url: {{ .Values.actuator.opentelemetry.metrics.export.url }}
