apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "booking.fullname" . }}-config
  labels:
    {{- include "booking.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      profiles:
        active: {{ .Values.spring.profiles.active | quote }}
      config:
        import: "optional:file:/etc/config-secret/application.yaml"
      datasource:
        url: {{ .Values.database.url }}
        username: {{ .Values.database.username }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.oauth2.issuerUri }}
          client:
            registration:
              rooms:
                provider: keycloak
                client-id: {{ .Values.oauth2.clientId }}
                client-secret: {{ .Values.oauth2.clientSecret }}
                authorization-grant-type: client_credentials
            provider:
              keycloak:
                issuer-uri: {{ .Values.oauth2.issuerUri }}
    management:
      endpoint:
        health:
          probes:
            enabled: {{ .Values.actuator.health.probesEnabled }}
      endpoints:
        web:
          exposure:
            include: {{ .Values.actuator.endpoints.exposure.include | quote }}
      prometheus:
        metrics:
          export:
            enabled: {{ .Values.actuator.prometheus.metrics.export.enabled }}
      {{- $otlp := .Values.actuator.opentelemetry }}
      {{- if $otlp.tracing.export.otlp.endpoint }}
      opentelemetry:
        tracing:
          export:
            otlp:
              transport: {{ $otlp.tracing.export.otlp.transport }}
              endpoint: {{ $otlp.tracing.export.otlp.endpoint }}
              {{- if $otlp.tracing.export.otlp.headers }}
              headers:
              {{- $otlp.tracing.export.otlp.headers | toYaml | nindent 16 }}
              {{- end }}
        {{- if $otlp.resourceAttributes }}
        resource-attributes:
        {{- $otlp.resourceAttributes | toYaml | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- $metricsOtlp := $otlp.metrics.export }}
      otlp:
        metrics:
          export:
            enabled: {{ $metricsOtlp.enabled }}
            {{- if $metricsOtlp.url }}
            url: {{ $metricsOtlp.url }}
            {{- end }}
            {{- if $metricsOtlp.headers }}
            headers:
              {{- $metricsOtlp.headers | toYaml | nindent 14 }}
            {{- end }}
