{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secret.name | default (printf "%s-db-secret" (include "booking.fullname" .)) }}
  labels:
    {{- include "booking.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.secret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.store.name | default (include "booking.fullname" .) }}
    kind: {{ .Values.externalSecrets.store.type }}
  target:
    name: {{ .Values.externalSecrets.secret.name | default (printf "%s-db-secret" (include "booking.fullname" .)) }}
    creationPolicy: {{ .Values.externalSecrets.secret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.secret.deletionPolicy }}
    template:
      data:
        application.yaml: |
          spring:
            datasource:
              password: "{{ "{{" }} .password {{ "}}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.secret.remoteRef.key }}
        property: {{ .Values.externalSecrets.secret.remoteRef.property }}
{{- end }}
