{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: {{ .Values.externalSecrets.store.type }}
metadata:
  name: {{ .Values.externalSecrets.store.name | default (include "booking.fullname" .) }}
  labels:
    {{- include "booking.labels" . | nindent 4 }}
spec:
  {{- $storeSpec := .Values.externalSecrets.store.spec }}
  {{- if $storeSpec }}
  {{- toYaml $storeSpec | nindent 2 }}
  {{- end }}
{{- end }}
